/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ruemcdfbgahmnjuqzfri"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1ZW1jZGZiZ2FobW5qdXF6ZnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2ODM5MzAsImV4cCI6MjA3NTI1OTkzMH0.gt2tArMsyI1jUFOZzBYDBabKVzcFKj6-J5PF0mE-0Zs"